#ifndef MONOLITH_KEMPARAMS_H
#define MONOLITH_KEMPARAMS_H

#define KEMK 4
#define KEMN 256
#define KEMQ 3329

#define KEMSYMBYTES 32
#define KEMSSBYTES  32

#define KEMPOLYBYTES    384
#define KEMPOLYVECBYTES (KEMK * KEMPOLYBYTES)

#define KEMETA1 2
#define KEMETA2 2

#define KEMPOLYCOMPRESSEDBYTES    160
#define KEMPOLYVECCOMPRESSEDBYTES (KEMK * 352)

#define KEMINDCPAMSGBYTES       (KEMSYMBYTES)
#define KEMINDCPAPUBKEYBYTES    (KEMPOLYVECBYTES + KEMSYMBYTES)
#define KEMINDCPASECKEYBYTES    (KEMPOLYVECBYTES)
#define KEMINDCPACTBYTES        (KEMPOLYVECCOMPRESSEDBYTES + KEMPOLYCOMPRESSEDBYTES)

#define KEMPUBKEYBYTES (KEMINDCPAPUBKEYBYTES)
#define KEMSECKEYBYTES (KEMINDCPASECKEYBYTES + KEMINDCPAPUBKEYBYTES + 2 * KEMSYMBYTES)
#define KEMCTBYTES     (KEMINDCPACTBYTES)

#define KEMMONT (-1044)
#define KEMQINV (-3327)

#endif
